import { Bank, Folder, Voucher } from "@/interfaces";

interface SeedData {
    folders: Folder[],
    banks: Bank[],
    vouchers: Voucher[]
}

const seedDocuments = [
    {
        scanEntryDate: new Date(),
        pages: 10,
        observations: 'MARLON LAGUNA SALGADO',
        scanExitDate: new Date(), 
    },
]

const seedBanks : Bank[] =  [
    {
        name:"ac lobortis",
        account:'5',
        internalAccount:'11'
    },
    {
        name:"at velit",
        account:'3',
        internalAccount:'2'
    },
        
    {
        name:"lacus morbi sem",
        account:'12',
        internalAccount:'2'
    },
    {
        name:"magna vestibulum aliquet",
        account:'3',
        internalAccount:'12'
    },
    {
        name:"nulla neque",
        account:'1',
        internalAccount:'10'
    }
]

export const initialData: SeedData = {
    folders: [
        {
            scanEntryDate: new Date(),
            number : '134.1',
            month  : 11,
            year   : 2022,
            firstVoucher : 66318,
            lastVoucher  : 66333,
            observations : 'El CK66318 y CK66319 no se adjuntaron ya que estos pertencen al mes de octubre del 2022',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '135',
            month  : 11,
            year   : 2022,
            firstVoucher : 66334,
            lastVoucher  : 66357,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '136',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '137',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '138',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '139',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '140',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '141',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '142',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '143',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '144',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '145',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '146',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '147',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '148',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '149',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '150',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '151',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '152',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '153',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
    ],
    banks: seedBanks,
    vouchers: [
        {
            document: seedDocuments[0],
            folder: 135,
            bank: seedBanks[0],
            check : 66334,
            checkDate : new Date(),
            checkValue : 24431.72,
            isNull : false,
        },
        {
            document: seedDocuments[0],
            folder: 135,
            bank: seedBanks[0],
            check : 66335,
            checkDate : new Date(),
            checkValue : 5682,
            isNull : false,
        },
        {
            document: seedDocuments[0],
            folder: 135,
            bank: seedBanks[2],
            check : 66336,
            checkDate : new Date(),
            checkValue : 3172,
            isNull : false,
        },
        {
            document: seedDocuments[0],
            folder: 135,
            bank: seedBanks[3],
            check : 66337,
            checkDate : new Date(),
            checkValue : 4317,
            isNull : false,
        },
        {
            document: seedDocuments[0],
            folder: 136,
            bank: seedBanks[0],
            check : 66358,
            checkDate : new Date(),
            checkValue : 24431,
            isNull : false,
        },
        {
            document: seedDocuments[0],
            folder: 136,
            bank: seedBanks[1],
            check : 66359,
            checkDate : new Date(),
            checkValue : 1002,
            isNull : false,
        },
        {
            document: seedDocuments[0],
            folder: 136,
            bank: seedBanks[2],
            check : 66360,
            checkDate : new Date(),
            checkValue : 2431.72,
            isNull : false,
        },
    ]
}

