import { Folder } from "@/interfaces";

interface SeedData {
    folders: Folder[],
}

export const initialData: SeedData = {
    folders: [
        {
            scanEntryDate: new Date(),
            number : '134.1',
            month  : 11,
            year   : 2022,
            firstVoucher : 66318,
            lastVoucher  : 66333,
            observations : 'El CK66318 y CK66319 no se adjuntaron ya que estos pertencen al mes de octubre del 2022',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '135',
            month  : 11,
            year   : 2022,
            firstVoucher : 66334,
            lastVoucher  : 66357,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '136',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '137',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '138',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '139',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '140',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '141',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '142',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '143',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '144',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '145',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '146',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '147',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '148',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '149',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '150',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '151',
            month  : 11,
            year   : 2022,
            firstVoucher : 66358,
            lastVoucher  : 66366,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '152',
            month  : 11,
            year   : 2022,
            firstVoucher : 66367,
            lastVoucher  : 66399,
            observations : '',
            scanExitDate : new Date(),
        },
        {
            scanEntryDate: new Date(),
            number : '153',
            month  : 11,
            year   : 2022,
            firstVoucher : 66400,
            lastVoucher  : 66422,
            observations : '',
            scanExitDate : new Date(),
        },
    ]
}

